### ISSUE TITLE
Wunschliste VTK Demos mit der Vive

### ISSUE THREAD

**Issue by MBrill** [MBrill/VTKExamples#7]
- Eine Liste von Demos aus den VTK C++ Examples, die wir auf die Vive portieren möchten
- Portieren der Examples und testen mit der Vive. Auch darauf überprüfen, welche Interaktionen möglich und sinnvoll sind.
- C++ und OpenVR
- feature

Hier die Wunschliste (die Namen beziehen sich auf die Github-Seite von Lorensen mit den VTK Examples:

- DEMReader
- ReadAllPolyDataTypes
- ReadPLY
- 3DSImporter
- DiscreteMarchingCubes
- Lorenz
- AnatomicalOrientation
- BluntStreamLines
- CarotidFlow
- CombustionSurface
- Office
- OfficeTube
- Lox
- LoxGrid
- LoxSeeds
- Kitchen
- Headbone

**Comment by mast0062** [comment]
DEMReader, BluntStreamLines und OfficeTube funktionieren noch nicht. Sonst funktionieren alle.

**Comment by mast0062** [comment]
Es funktionieren jetzt alle. Bei helloworld testen wir gerade mit dem InteractorStyle.
