### ISSUE TITLE
Added examples DEMReader, ReadPLY, ReadAllPolyDataTypes

### ISSUE THREAD

**Issue by mast0062** [MBrill/VTKExamples#8]
für die Ply examples nutzten wir eine horse.ply aus dem Internet. Sie ist in dem Source Ordner von ReadAllPolyDataTypes enthalten.

Haben Sie einen Vorrat an Ply oder Dem Dateien?

**Comment by MBrill** [comment]
Habe ich, muss ich raussuchen. Die PLY-Dateien kommen von Stanford, da gibt es noch den Buddha und den bunny. Wobei, wenn das mit dem Pferd läuft geht es mit den anderen Dateien auch - könnten wir also auch vorerst abhaken ...
